# Generated by Django 5.0.2 on 2024-09-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='landloard',
            new_name='landlord',
        ),
    ]
