# Generated by Django 5.0.2 on 2024-09-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_landloard_property_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country_code',
            field=models.CharField(max_length=20),
        ),
    ]
